import { type Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "Privacy Policy",
};


export default function Privacy() {

    return <div className={`font-visby whitespace-pre-line text-primaryWhite`} dangerouslySetInnerHTML={{
        __html: "        PRIVACY POLICY\n" +
            "\n" +
            "        AQELA Technologies SRL is committed to protecting your privacy. This Privacy Policy explains how your personal\n" +
            "        information is collected, used, and disclosed.\n" +
            "        This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”)\n" +
            "        alongside our AQELA Website. By accessing or using our Service, you signify that you have read, understood, and\n" +
            "        agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy\n" +
            "        Policy and our Terms of Service.\n" +
            "        Our Privacy Policy was last updated on 30. 05. 2023.\n" +
            "\n" +
            "        1 CONTACT DETAILS\n" +
            "        Our full details are:\n" +
            "        Name of legal entity: AQELA Technologies SRL.\n" +
            "        e-mail adress: office@aqela.org\n" +
            "        Adress: Tusnad, Str. Principala, nr. 191\n" +
            "\n" +
            "        2 DEFINITIONS AND KEY TERMS\n" +
            "        For the purposes of this Privacy Policy:\n" +
            "        \"Company\" (referred to as either \"the Company\", “Vendor”, \"We\", \"Us\" or \"Our\" in this Agreement) refers to AQELA\n" +
            "        Technologies SRL. that is responsible for your information under this Privacy Policy.\n" +
            "        \"Cookies\" small amount of data generated by a website and saved by your web browser. It is used to identify your\n" +
            "        browser, provide analytics, remember information about you such as your language preference or login\n" +
            "        information.\n" +
            "        \"Data Controller\", for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as\n" +
            "        the legal person which alone or jointly with others determines the purposes and means of the processing of\n" +
            "        Personal Data.\n" +
            "        \"Device\" means any internet connected device such as a phone, tablet, computer or any other device that can be\n" +
            "        used to use the services.\n" +
            "        \"Personal Data\" is any information that relates to an identified or identifiable individual, such as a name, an\n" +
            "        identification number, location data, online identifier or to one or more factors specific to the physical,\n" +
            "        physiological, genetic, mental, economic, cultural or social identity.\n" +
            "        “Personnel” refers to those individuals who are employed by the Company or are under contract to perform a\n" +
            "        service on behalf of one of the parties.\n" +
            "        \"Service\" refers to the service provided by the Company as described in the relative terms of service and on\n" +
            "        this platform.\n" +
            "        \"Usage Data\" refers to data collected automatically, either generated by the use of the Service or from the\n" +
            "        Service infrastructure itself (for example, the duration of a page visit). Usage Data may include information\n" +
            "        such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of\n" +
            "        our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device\n" +
            "        identifiers and other diagnostic data.\n" +
            "        When You access the Service by or through a mobile device, we may collect certain information automatically,\n" +
            "        including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address\n" +
            "        of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device\n" +
            "        identifiers and other diagnostic data.\n" +
            "        We may also collect information that Your browser sends whenever You visit our Service or when You access the\n" +
            "        Service by or through a mobile device.\n" +
            "\n" +
            "        3 TYPES OF DATA COLLECTED\n" +
            "        While using our Service, we may ask You to provide us with certain personally identifiable information that can\n" +
            "        be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n" +
            "        ● Usage Data\n" +
            "        The security of Your Data is important to Us, but remember that no method of transmission over the Internet, or\n" +
            "        method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect\n" +
            "        Your Personal Data, we cannot guarantee its absolute security.\n" +
            "\n" +
            "        4 USE OF YOUR PERSONAL DATA\n" +
            "        The Company may use Personal Data for the following purposes:\n" +
            "        ● To provide and maintain our Service, including to monitor the usage of our Service.\n" +
            "        ● To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide\n" +
            "        can give You access to different functionalities of the Service that are available to You as a registered user.\n" +
            "        ● For the performance of a contract: the development, compliance and undertaking of the purchase contract for\n" +
            "        the products, items or services You have purchased or of any other contract with Us through the Service.\n" +
            "        ● To contact You: To contact You by email, or other equivalent forms of electronic communication, such as a\n" +
            "        mobile application's push notifications regarding updates or informative communications related to the\n" +
            "        functionalities, products or contracted services, including the security updates, when necessary or reasonable\n" +
            "        for their implementation.\n" +
            "        ● To provide You with news, special offers and general information about other goods, services and events which\n" +
            "        we offer that are similar to those that you have already purchased or enquired about unless You have opted not\n" +
            "        to receive such information.\n" +
            "        ● To manage Your requests: To attend and manage Your requests to Us.\n" +
            "        ● For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,\n" +
            "        restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a\n" +
            "        going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us\n" +
            "        about our Service users is among the assets transferred.\n" +
            "        ● For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage\n" +
            "        trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service,\n" +
            "        products, services, marketing and your experience.\n" +
            "\n" +
            "        We may share Your personal information in the following situations:\n" +
            "        ● With Service Providers: We may share Your personal information with Service Providers to monitor and analyze\n" +
            "        the use of our Service, for payment processing, to contact You.\n" +
            "        ● For business transfers: We may share or transfer Your personal information in connection with, or during\n" +
            "        negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our\n" +
            "        business to another company.\n" +
            "        ● With Affiliates: We may share Your information with Our affiliates, in which case we will require those\n" +
            "        affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint\n" +
            "        venture partners or other companies that We control or that are under common control with Us.\n" +
            "        ● For Law enforcement: Under certain circumstances, the Company may be required to disclose Your Personal Data\n" +
            "        if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government\n" +
            "        agency).\n" +
            "        ● For other legal requirements: The Company may disclose Your Personal Data in the good faith belief that such\n" +
            "        action is necessary to: comply with a legal obligation; protect and defend the rights or property of the\n" +
            "        Company; prevent or investigate possible wrongdoing in connection with the Service; protect against legal\n" +
            "        liability; etc.\n" +
            "        ● With business partners: We may share Your information with Our business partners to offer You certain\n" +
            "        products, services or promotions.\n" +
            "        ● With Your consent: We may disclose Your personal information for any other purpose with Your consent.\n" +
            "\n" +
            "        5 RETENTION OF YOUR PERSONAL DATA\n" +
            "        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this\n" +
            "        Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal\n" +
            "        obligations (for example, if we are required to retain your data to comply with applicable laws), resolve\n" +
            "        disputes, and enforce our legal agreements and policies.\n" +
            "        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a\n" +
            "        shorter period of time, except when this data is used to strengthen the security or to improve the functionality\n" +
            "        of Our Service, or We are legally obligated to retain this data for longer time periods.\n" +
            "\n" +
            "        6 TRANSFER OF YOUR PERSONAL DATA\n" +
            "        Your information, including Personal Data, is processed at the Company's operating offices and in any other\n" +
            "        places where the parties involved in the processing are located. It means that this information may be\n" +
            "        transferred to — and maintained on — computers located outside of Your state, province, country or other\n" +
            "        governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.\n" +
            "        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to\n" +
            "        that transfer.\n" +
            "        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in\n" +
            "        accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or\n" +
            "        a country unless there are adequate controls in place including the security of Your data and other personal\n" +
            "        information.\n" +
            "\n" +
            "        7 THIRD PARTY DATA PROCESSING\n" +
            "        The Service Providers we use may have access to Your Personal Data. These third-party vendors collect, store,\n" +
            "        use, process and transfer information about Your activity on Our Service in accordance with their Privacy\n" +
            "        Policies.\n" +
            "        We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other\n" +
            "        information that may be of interest to You. You may opt-out of receiving any, or all, of these communications\n" +
            "        from Us by following the unsubscribe link or instructions provided in any email we send or by contacting Us.\n" +
            "        We may provide paid products and/or services within the Service. In that case, we may use third party services\n" +
            "        for payment processing (e.g. payment processors).\n" +
            "        We will not store or collect Your payment card details. That information is provided directly to Our third-party\n" +
            "        payment processors whose use of Your personal information is governed by their Privacy Policy. These payment\n" +
            "        processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a\n" +
            "        joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure\n" +
            "        the secure handling of payment information.\n" +
            "\n" +
            "        8 COOKIE POLICY\n" +
            "        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain\n" +
            "        information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to\n" +
            "        improve and analyze Our Service. The technologies We use may include:\n" +
            "        ● Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to\n" +
            "        refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may\n" +
            "        not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will\n" +
            "        refuse Cookies, our Service may use Cookies.\n" +
            "        ● Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web\n" +
            "        beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for\n" +
            "        example, to count users who have visited those pages or opened an email and for other related website statistics\n" +
            "        (for example, recording the popularity of a certain section and verifying system and server integrity).\n" +
            "\n" +
            "        Cookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on Your personal computer or mobile\n" +
            "        device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.\n" +
            "\n" +
            "        We use both Session and Persistent Cookies for the purposes set out below:\n" +
            "        ● Necessary / Essential Cookies (Session Cookies): These Cookies are essential to provide You with services\n" +
            "        available through the Website and to enable You to use some of its features. They help to authenticate users and\n" +
            "        prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be\n" +
            "        provided, and We only use these Cookies to provide You with those services.\n" +
            "        ● Cookies Policy / Notice Acceptance Cookies (Persistent Cookies): These Cookies identify if users have accepted\n" +
            "        the use of cookies on the Website.\n" +
            "        ● Functionality Cookies (Persistent Cookies): These Cookies allow us to remember choices You make when You use\n" +
            "        the Website, such as remembering your login details or language preference. The purpose of these Cookies is to\n" +
            "        provide You with a more personal experience and to avoid You having to re-enter your preferences every time You\n" +
            "        use the Website.\n" +
            "        ● Tracking and Performance Cookies (Persistent Cookies): These Cookies are used to track information about\n" +
            "        traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or\n" +
            "        indirectly identify you as an individual visitor. This is because the information collected is typically linked\n" +
            "        to a pseudonymous identifier associated with the device you use to access the Website. We may also use these\n" +
            "        Cookies to test new pages, features or new functionality of the Website to see how our users react to them.\n" +
            "\n" +
            "        9 GDPR PRIVACY POLICY\n" +
            "        We may process Personal Data under the following conditions, or under the conditions set out in Section 4 of\n" +
            "        this Policy:\n" +
            "        ● Consent: You have given Your consent for processing Personal Data for one or more specific purposes.\n" +
            "        ● Performance of a contract: Provision of Personal Data is necessary for the performance of an agreement with\n" +
            "        You and/or for any pre-contractual obligations thereof.\n" +
            "        ● Legal obligations: Processing Personal Data is necessary for compliance with a legal obligation to which the\n" +
            "        Company is subject.\n" +
            "        ● Vital interests: Processing Personal Data is necessary in order to protect Your vital interests or of another\n" +
            "        natural person.\n" +
            "        ● Public interests: Processing Personal Data is related to a task that is carried out in the public interest or\n" +
            "        in the exercise of official authority vested in the Company.\n" +
            "        ● Legitimate interests: Processing Personal Data is necessary for the purposes of the legitimate interests\n" +
            "        pursued by the Company.\n" +
            "        In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing,\n" +
            "        and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a\n" +
            "        requirement necessary to enter into a contract.\n" +
            "        The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise\n" +
            "        Your rights.\n" +
            "\n" +
            "        You have the right under this Privacy Policy, and by law if You are within the EU, to:\n" +
            "        ● Request access to Your Personal Data. The right to access, update or delete the information We have on You.\n" +
            "        Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your\n" +
            "        account settings section. If you are unable to perform these actions yourself, please contact Us to assist You.\n" +
            "        This also enables You to receive a copy of the Personal Data We hold about You.\n" +
            "        ● Request correction of the Personal Data that We hold about You. You have the right to have any incomplete or\n" +
            "        inaccurate information We hold about You corrected.\n" +
            "        ● Object to processing of Your Personal Data. This right exists where We are relying on a legitimate interest as\n" +
            "        the legal basis for Our processing and there is something about Your particular situation, which makes You want\n" +
            "        to object to our processing of Your Personal Data on this ground. You also have the right to object where We are\n" +
            "        processing Your Personal Data for direct marketing purposes.\n" +
            "        ● Request erasure of Your Personal Data. You have the right to ask Us to delete or remove Personal Data when\n" +
            "        there is no good reason for Us to continue processing it.\n" +
            "        ● Request the transfer of Your Personal Data. We will provide to You, or to a third-party You have chosen, Your\n" +
            "        Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies\n" +
            "        to automated information which You initially provided consent for Us to use or where We used the information to\n" +
            "        perform a contract with You.\n" +
            "        ● Withdraw Your consent. You have the right to withdraw Your consent on using your Personal Data. If You\n" +
            "        withdraw Your consent, we may not be able to provide You with access to certain specific functionalities of the\n" +
            "        Service.\n" +
            "        You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note\n" +
            "        that we may ask You to verify Your identity before responding to such requests. If You make a request, we will\n" +
            "        try our best to respond to You as soon as possible. For more information, if You are in the European Economic\n" +
            "        Area (EEA), please contact Your local data protection authority in the EEA.\n" +
            "\n" +
            "        10 CCPA PRIVACY POLICY\n" +
            "        This privacy notice section for California residents applies solely to all visitors, users, and others who\n" +
            "        reside in the State of California.\n" +
            "        We collect information that identifies, relates to, describes, references, is capable of being associated with,\n" +
            "        or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a\n" +
            "        list of categories of personal information which we may collect from California residents. We may use or\n" +
            "        disclose those categories of personal information for business or commercial purposes, as set out in Section 4\n" +
            "        of this Policy.\n" +
            "        ● Identifiers (e.g. real name, alias, postal address, unique personal identifier, online identifier, Internet\n" +
            "        Protocol address, email address, account name, driver's license number, passport number, or other similar\n" +
            "        identifiers)\n" +
            "        ● Personal information categories listed in the California Customer Records statute (Cal. Civ. Code §\n" +
            "        1798.80(e)). (e.g. name, signature, Social Security number, physical characteristics or description, address,\n" +
            "        telephone number, passport number, etc.)\n" +
            "        ● Commercial information (e.g. records and history of products or services purchased or considered)\n" +
            "        ● Internet or other similar network activity (e.g. interaction with our Service or advertisement)\n" +
            "        Please note that the categories listed above are those defined in the CCPA. This does not mean that all examples\n" +
            "        of that category of personal information were in fact disclosed, but reflects our good faith belief to the best\n" +
            "        of our knowledge that some of that information from the applicable category may be and may have been disclosed.\n" +
            "        When We disclose personal information for a business purpose or a commercial purpose, we enter a contract that\n" +
            "        describes the purpose and requires the recipient to both keep that personal information confidential and not use\n" +
            "        it for any purpose except performing the contract.\n" +
            "\n" +
            "        Under CCPA, personal information does not include:\n" +
            "        ● Publicly available information from government records\n" +
            "        ● Deidentified or aggregated consumer information\n" +
            "        ● Information excluded from the CCPA's scope, such as:\n" +
            "        Health or medical information covered by the Health Insurance Portability and Accountability Act of 1996 (HIPAA)\n" +
            "        and the California Confidentiality of Medical Information Act (CMIA) or clinical trial data\n" +
            "        Personal Information covered by certain sector-specific privacy laws, including the Fair Credit Reporting Act\n" +
            "        (FRCA), the Gramm-Leach-Bliley Act (GLBA) or California Financial Information Privacy Act (FIPA), and the\n" +
            "        Driver's Privacy Protection Act of 1994\n" +
            "\n" +
            "        We obtain the categories of personal information listed above from the following categories of sources:\n" +
            "        ● Directly from You. For example, from the forms You complete on our Service, preferences You express or provide\n" +
            "        through our Service, or from Your purchases on our Service.\n" +
            "        ● Indirectly from You. For example, from observing Your activity on our Service.\n" +
            "        ● Automatically from You. For example, through cookies We or our Service Providers set on Your Device as You\n" +
            "        navigate through our Service.\n" +
            "        ● From Service Providers. For example, third-party vendors to monitor and analyze the use of our Service,\n" +
            "        third-party vendors for payment processing, or other third-party vendors that We use to provide the Service to\n" +
            "        You.\n" +
            "\n" +
            "        The CCPA provides California residents with specific rights regarding their personal information. If You are a\n" +
            "        resident of California, You have the following rights:\n" +
            "        ● The right to notice. You have the right to be notified which categories of Personal Data are being collected\n" +
            "        and the purposes for which the Personal Data is being used.\n" +
            "        ● The right to request. Under CCPA, You have the right to request that We disclose information to You about Our\n" +
            "        collection, use, sale, disclosure for business purposes and share of personal information. Once We receive and\n" +
            "        confirm Your request, We will disclose to You:\n" +
            "        • The categories of personal information We collected about You\n" +
            "        • The categories of sources for the personal information We collected about You\n" +
            "        • Our business or commercial purpose for collecting or sharing that personal information\n" +
            "        • The categories of third parties with whom We share that personal information\n" +
            "        • The specific pieces of personal information We collected about You\n" +
            "        • If we sold Your personal information or disclosed Your personal information for a business purpose, We will\n" +
            "        disclose to You:\n" +
            "        The categories of personal information categories shared\n" +
            "        The categories of personal information categories disclosed\n" +
            "        ● The right to say no to the disclosure of Personal Data (opt-out). You have the right to direct Us to not share\n" +
            "        Your personal information. To submit an opt-out request please contact Us.\n" +
            "        ● The right to delete Personal Data. You have the right to request the deletion of Your Personal Data, subject\n" +
            "        to certain exceptions. Once We receive and confirm Your request, We will delete (and direct Our Service\n" +
            "        Providers to delete) Your personal information from our records, unless an exception applies.\n" +
            "        ● The right not to be discriminated against. You have the right not to be discriminated against for exercising\n" +
            "        any of Your consumer's rights, including by:\n" +
            "        • Denying goods or services to You\n" +
            "        • Charging different prices or rates for goods or services, including the use of discounts or other benefits or\n" +
            "        imposing penalties\n" +
            "        • Providing a different level or quality of goods or services to You\n" +
            "        • Suggesting that You will receive a different price or rate for goods or services or a different level or\n" +
            "        quality of goods or services\n" +
            "        In order to exercise any of Your rights under the CCPA, and if You are a California resident, You can contact\n" +
            "        Us.\n" +
            "\n" +
            "        11 MINORS’ PRIVACY\n" +
            "        We do not knowingly collect personal information from minors through our Service, although certain third-party\n" +
            "        websites that we link to may do so. These third-party websites have their own terms of use and privacy policies\n" +
            "        and we encourage parents and legal guardians to monitor their children's Internet usage and instruct their\n" +
            "        children to never provide information on other websites without their permission.\n" +
            "        We do not disclose or share the personal information of Consumers we actually know to be less than 16 years of\n" +
            "        age, unless we receive affirmative authorization (the \"right to opt-in\") from either the Consumer who is between\n" +
            "        13 and 16 years of age, or the parent or guardian of a Consumer less than 13 years of age. Our Service does not\n" +
            "        address anyone under the age of 13. Consumers who opt-in to the sale of personal information may opt-out of\n" +
            "        future sales at any time. To exercise the right to opt-out, You (or Your authorized representative) may submit a\n" +
            "        request to Us by contacting Us.\n" +
            "        If You have reason to believe that a minor has provided Us with personal information, please contact Us with\n" +
            "        sufficient detail to enable Us to delete that information.\n" +
            "\n" +
            "        12 CHANGES TO THIS PRIVACY POLICY\n" +
            "        If We decide to collect additional categories of personal information or use the personal information We\n" +
            "        collected for materially different, unrelated, or incompatible purposes We will update this Privacy Policy. We\n" +
            "        will notify You of any changes by posting the new Privacy Policy on this page.\n" +
            "        We will let You know via e-mail and/or a prominent notice on Our Service, prior to the change becoming effective\n" +
            "        and update the \"Last updated\" date at the top of this Privacy Policy.\n" +
            "        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are\n" +
            "        effective when they are posted on this page.\n" +
            "\n" +
            "        13 CONTACT US\n" +
            "        For any other information, clarifications, submission of any request, such as contacting the webmaster or\n" +
            "        request for reproduction rights of any part of the content of the website, as well as for requests for approval\n" +
            "        of reproduction of content you can contact us:\n" +
            "        ● via e-mail: office@aqela.org\n" +
            "\n"
    }}>

    </div>
}
